# Generated by Django 4.1.2 on 2025-11-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=1.7, max_digits=3),
            preserve_default=False,
        ),
    ]
