# Generated by Django 4.1.2 on 2025-12-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_datos_altura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='datos',
            name='perfil',
            field=models.CharField(blank=True, choices=[('estudiante', 'Estudiante')], default='estudiante', max_length=15, null=True),
        ),
    ]
